### ISSUE TITLE
Condition to go to prod for autumn experimentation 🍂

### ISSUE THREAD

**Issue by heroinedor** [eimis-ans/eimis-synapse#128]
Conditions to fulfill to go to prod only for the first experimentation.
Not relevant for the final production.

checklist :
- [x] configure URL
- [x] HDS hosting ⚠️
- [x] update GHA workflow with relevant vars
- [x] User Registration script : mail + password + display name ? #130 
- [x] Deletion of keycloak #129 
- [x] Discovery room : onboarding process #126
- [x] Configuration of display name #51
- [x] Test with mobile app to be sure that everything is ok
- [x] Plug synapse on a  production SMTP service #152 
- [x] Disable auto register #131
- [x] Deactivate / hide PSC access (optional)
- [x] close the federation #145

**Comment by ad2ien** [comment]
Enrollment :
- Users are created with a script
- We tell the users with a common e-mail to re-initialize their password (forgotten password)

**Comment by heroinedor** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EIMIS-6419ddbd85693a00127de149/issues/eimis-ans/eimis-synapse/128?planning-poker) with Zenhub @ad2ien

**Comment by heroinedor** [comment]
Each issue estimated separately give a final estimate of 16
BUT there is a big warning on HDS hosting that can be wether easy and smal or complex and long

**Comment by ad2ien** [comment]
Teams bridge, PSC login and email sender parameters added and set on prod, preprod, develop environment.
Preprod PR : https://github.com/eimis-ans/eimis-synapse/pull/154
